src/RefitWithRazorPagesDemo.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RefitWithRazorPagesDemo.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

src/RefitWithRazorPagesDemo.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RefitWithRazorPagesDemo.Web.Services;

namespace RefitWithRazorPagesDemo.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public async Task OnGet()
        {
        }
    }
}

src/RefitWithRazorPagesDemo.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RefitWithRazorPagesDemo.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

src/RefitWithRazorPagesDemo.Web/Pages/Products/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RefitWithRazorPagesDemo.DataAccessLayer.Dtos;
using RefitWithRazorPagesDemo.Web.Services;

namespace RefitWithRazorPagesDemo.Web.Pages.Products
{
    public class CreateModel : PageModel
    {
        private readonly IProductService _productService;

        [BindProperty]
        public ProductToUpsertDto ProductToUpsertDto { get; set; } = new ProductToUpsertDto();

        public string ErrorMessage { get; set; } = string.Empty;

        public bool HasError { get; set; } = false;

        public CreateModel(IProductService productService)
        {
            _productService = productService;
        }

        public void OnGet()
        {

        }

        public async Task OnPost()
        {
            if (ProductToUpsertDto.Price < 10)
                ModelState.AddModelError("Error", "Price should be greater than 10 Euros");

            if (!ModelState.IsValid)
            {
                ErrorMessage = ModelState["Error"]!.Errors[0].ErrorMessage;
                HasError = true;
                return;
            }

            await _productService.CreateProduct(ProductToUpsertDto);
            Response.Redirect("Index");

        }
    }
}

src/RefitWithRazorPagesDemo.Web/Pages/Products/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RefitWithRazorPagesDemo.DataAccessLayer.Dtos;
using RefitWithRazorPagesDemo.Domain.Entities;
using RefitWithRazorPagesDemo.Web.Services;
using System.Runtime.CompilerServices;

namespace RefitWithRazorPagesDemo.Web.Pages.Products
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public ProductToUpsertDto ProductToUpdate { get; set; } = new ProductToUpsertDto();
        public string ErrorMessage { get; set; } = string.Empty;
        public bool HasError { get; set; } = false;

        private readonly IProductService _productService;

        public EditModel(IProductService productService)
        {
            _productService = productService;
        }

        public async Task OnGet(int? productId)
        {
            if (productId == null)
                Response.Redirect("Index");

            var product = await _productService.GetProductById(productId!.Value);

            if (product == null)
                Response.Redirect("Index");

            ProductToUpdate.Name = product.Name;
            ProductToUpdate.Category = product.Category;
            ProductToUpdate.Price = product.Price;
            ProductToUpdate.CreatedAt = product.CreatedAt;
        }

        public async Task OnPost(int? productId)
        {

            if (productId == null)
                Response.Redirect("Index");

            if (ProductToUpdate.Price < 10)
                ModelState.AddModelError("Error", "Price should be greater than 10 Euros");

            if (!ModelState.IsValid)
            {
                ErrorMessage = ModelState["Error"]!.Errors[0].ErrorMessage;
                HasError = true;
            }
            else
            {
                await _productService.UpdateProduct(productId.Value, ProductToUpdate);
                Response.Redirect("Index");
            }
        }
    }
}

src/RefitWithRazorPagesDemo.Web/Pages/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RefitWithRazorPagesDemo.Domain.Entities;
using RefitWithRazorPagesDemo.Web.Services;

namespace RefitWithRazorPagesDemo.Web.Pages.Products
{
    public class IndexModel : PageModel
    {
        private readonly IProductService _productService;
        public List<Product> Products { get; set; }=new List<Product>();
        public IndexModel(ILogger<IndexModel> logger, IProductService productService)
        {
            _productService = productService;
        }

        public async Task OnGet()
        {
            Products = await _productService.GetProducts();
        }

        public async Task OnPostButtonDelete(int id)
        {
            await _productService.DeleteProduct(id);
            Response.Redirect("/Products/Index");
        }
    }
}

src/RefitWithRazorPagesDemo.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p><a href="/Products/index">Go To Products</a></p>
</div>

src/RefitWithRazorPagesDemo.Web/Pages/Products/Create.cshtml
@page
@model RefitWithRazorPagesDemo.Web.Pages.Products.CreateModel
@{
}

@if(Model.HasError)
{
    <div class="alert alert-danger" role="alert">
        @Model.ErrorMessage
    </div>
}


<form method="post">
    <div class="row mb-3">
        <label for="exampleInputEmail1" class="form-label">Name</label>
        <input class="form-control" asp-for="ProductToUpsertDto.Name">
        <span asp-validation-for="ProductToUpsertDto.Name" class="text-danger"></span>
    </div>

    <div class="row mb-3">
        <label for="exampleInputEmail1" class="form-label">Category</label>
        <select class="form-select" asp-for="ProductToUpsertDto.Category">
            <option selected>Select</option>
            <option value="Mobile">Mobile</option>
            <option value="TV">TV</option>
            <option value="Laptop">Laptop</option>
        </select>
        <span asp-validation-for="ProductToUpsertDto.Category" class="text-danger"></span>
    </div>

    <div class="row mb-3">
        <label for="exampleInputEmail1" class="form-label">Price</label>
        <input class="form-control" asp-for="ProductToUpsertDto.Price">
        <span asp-validation-for="ProductToUpsertDto.Price" class="text-danger"></span>
    </div>

    <div class="row mb-3">
        <label for="exampleInputEmail1" class="form-label">Created At</label>
        <input class="form-control" asp-for="ProductToUpsertDto.CreatedAt">
        <span asp-validation-for="ProductToUpsertDto.CreatedAt" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="submit" class="btn btn-info">Cancel</button>
</form>

src/RefitWithRazorPagesDemo.Web/Pages/Products/Edit.cshtml
@page
@model RefitWithRazorPagesDemo.Web.Pages.Products.EditModel
@{

}
@if (Model.HasError)
{
    <div class="alert alert-danger" role="alert">
        @Model.ErrorMessage
    </div>
}
<form method="post">
    <div class="row mb-3">
        <label for="exampleInputEmail1" class="form-label">Name</label>
        <input class="form-control" asp-for="@Model.ProductToUpdate.Name">
        <span asp-validation-for="ProductToUpdate.Name" class="text-danger"></span>
    </div>

    <div class="row mb-3">
        <label for="exampleInputEmail1" class="form-label">Category</label>
        <select class="form-select" asp-for="@Model.ProductToUpdate.Category">
            <option selected>Select</option>
            <option value="Mobile">Mobile</option>
            <option value="TV">TV</option>
            <option value="Laptop">Laptop</option>
        </select>
        <span asp-validation-for="ProductToUpdate.Category" class="text-danger"></span>
    </div>

    <div class="row mb-3">
        <label for="exampleInputEmail1" class="form-label">Price</label>
        <input class="form-control" asp-for="@Model.ProductToUpdate.Price">
        <span asp-validation-for="ProductToUpdate.Price" class="text-danger"></span>
    </div>

    <div class="row mb-3">
        <label for="exampleInputEmail1" class="form-label">Created At</label>
        <input class="form-control" asp-for="@Model.ProductToUpdate.CreatedAt">
        <span asp-validation-for="ProductToUpdate.CreatedAt" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

src/RefitWithRazorPagesDemo.Web/Pages/Products/Index.cshtml
@page
@model RefitWithRazorPagesDemo.Web.Pages.Products.IndexModel
@{

}

<a class="btn btn-success btn-sm" href="/products/Create">Create New Product</a>
<br />

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col">Price</th>
            <th scope="col">Created At</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Products)
        {
            <tr>
                <th scope="row">@product.Id</th>
                <th scope="row">@product.Name</th>
                <th scope="row">@product.Category</th>
                <th scope="row">@product.Price</th>
                <th scope="row">@product.CreatedAt.ToString("dd.MM.yyyy")</th>
                <th scope="row">
                    <a class="btn btn-primary btn-sm" href="/products/Edit?productId=@product.Id">Edit</a>
                    <form class="form" method="post">
                        <input class="btn btn-danger btn-sm" type="submit" value="ButtonDelete" asp-page-handler="ButtonDelete" asp-route-id="@product.Id" />
                    </form>
                </th>
            </tr>
        }
    </tbody>
</table>

src/RefitWithRazorPagesDemo.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RefitWithRazorPagesDemo.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RefitWithRazorPagesDemo.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RefitWithRazorPagesDemo.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Products/index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RefitWithRazorPagesDemo.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>